#!/bin/sh

DESTINATION=
DIRECTORIES="bin var/log var/run etc"
FILES=

THISTOP=`pwd`

if [ -f "kvManagerd" ]; then
    mkdir -p bin
    cp -fupv kvManagerd bin
else
    echo "BUILD FIRST: `pwd`"
    exit 0
fi

echo "THISTOP: $THISTOP"

. $KVDIR/conf/INSTALL.conf





