#Major Makefile for decoder Library

# includefile contains Compiler definitions
TOP=../../..
include $(TOP)/conf/make.$(OSTYPE)
include $(TOP)/conf/common.mk

LIBNAME=decoder

LOCALIDIR=$(LOCALDIR)/include

