#! /bin/sh

## Prepare the database for test.


set -a  # export variables to the environment of subsequent commands
set -e  # Exit if a simple shell command fails
#set -x  # for debugging, remove later

if [ ! -f ~/.kvtest ]; then
	echo "The test config file is missing '~/.kvtest'"
	exit 1
fi

if ! [ $PGHOST ]; then
    echo "PGHOST er ikke satt! Avslutter..."
    exit 1
fi

## ** Global variables **
if ! [ $KVTEST ]; then
    echo "KVTEST er ikke satt! Avslutter..."
    exit 1
fi

if [ -z "$PGPASSWORD" ]; then
    PGPASSWORD=`grep dbpass $HOME/.kvpasswd | sed -e 's/ *dbpass *//'`
fi

PGDATABASE=kvalobs
PGUSER=kvalobs
psql -h $PGHOST -d $PGDATABASE -U $PGUSER < $KVTEST/test/sql/delete_data.sql

sqlite /var/kvalobs/kvsynop/kvsynopd.sqlite < $KVTEST/test/sql/delete_synop.sql
sqlite /var/kvalobs/agregate/database.sqlite < $KVTEST/test/sql/delete_agregator.sql

