#! /bin/sh

## Prepare the database for test.


set -a  # export variables to the environment of subsequent commands
set -e  # Exit if a simple shell command fails
#set -x  # for debugging, remove later


if ! [ $PGHOST ]; then
    echo "PGHOST er ikke satt! Avslutter..."
    exit 1
fi



## ** Global variables **
if ! [ $KVALOBS ]; then
    echo "KVALOBS er ikke satt! Avslutter..."
    exit 1
fi

if [ -z "$PGPASSWORD" ]; then
    PGPASSWORD=`grep dbpass $KVALOBS/.kvpasswd | sed -e 's/ *dbpass *//'`
fi

PGNAME=kvalobs
PGUSER=kvalobs
psql -h $PGHOST -d $PGNAME -U $PGUSER < $KVALOBS/share/kvalobs/test/delete_data.sql

sqlite $KVALOBS/var/kvsynop/kvsynopd.sqlite < $KVALOBS/share/kvalobs/test/delete_synop.sql
sqlite $KVALOBS/var/agregate/database.sqlite < $KVALOBS/share/kvalobs/test/delete_agregator.sql

