#! /bin/sh

KVDIR=$KVALOBS

export KVDIR 


#KVALOBSJAR=$KVDIR/share/kvalobs/java/lib/kvalobsclt.jar

#export CLASSPATH=$KVALOBSJAR:$CLASSPATH
#echo "CLASSPATH: $CLASSPATH"
#echo "$@"

$JAVA_HOME/bin/java  \
  "-DSQLHELPER_HOME=$KVALOBS"  \
  -jar $KVDIR/share/kvalobs/java/lib/SqlHelper.jar "$@"
    
