#!/bin/sh

QABASELOGDIR=$(kvconfig --localstatedir)/log/kvalobs/checks/

find $QABASELOGDIR -xdev -type d -ctime +7 -empty -exec rmdir --ignore-fail-on-non-empty {} \;
find $QABASELOGDIR -xdev -name '*.gz' -type f -mtime +7 -exec rm -f {} \;
find $QABASELOGDIR -xdev -type f -mtime +0 -not -name '*.gz' -exec gzip {} \;
