#! /bin/sh

QABASELOGDIR=$(kvconfig --localstatedir)/log/kvalobs/checks

find $QABASELOGDIR -xdev -type d -ctime +7 -empty -exec rmdir --ignore-fail-on-non-empty {} \;
find $QABASELOGDIR -xdev -name '*.log.gz' -type f -mtime +7 -exec rm -f {} \;
find $QABASELOGDIR -xdev -name '*.log' -type f -mtime +0 -exec gzip {} \;
