#!/bin/sh

LIBDIR=$(kvconfig --pkglibdir)

if [ ! -f "$LIBDIR/tool_funcs.sh" ]; then
	echo "Cant load: $LIBDIR/tool_funcs.sh"
	exit 1
fi

. $LIBDIR/tool_funcs.sh

#Exit if the machines do NOT hold the ipalias or is an test machine.
ipalias_status > /dev/null || exit 0 

QABASELOGDIR=$(kvconfig --localstatedir)/log/kvalobs/checks/

find $QABASELOGDIR -xdev -type d -ctime +7 -empty -exec rmdir --ignore-fail-on-non-empty {} \;
find $QABASELOGDIR -xdev -name '*.gz' -type f -mtime +7 -exec rm -f {} \;
find $QABASELOGDIR -xdev -type f -mtime +0 -not -name '*.gz' -exec gzip {} \;
