#Major Makefile for file Library

# includefile contains Compiler definitions
TOP=../../..

include $(TOP)/conf/make.$(OSTYPE)
include $(TOP)/conf/common.mk

export LIBNAME:=miutil


LOCALIDIR:=$(LOCALDIR)/include/$(LIBNAME)

export INCLUDE=-I$(PUTOOLS)/include         \
			   -I$(PUTOOLS)/include/puTools