# includefile contains Compiler definitions
TOP=../../..
include $(TOP)/conf/make.$(OSTYPE)
include $(TOP)/conf/common.mk

export LIBNAME:=kvdb

LOCALIDIR:=$(LOCALDIR)/include/$(LIBNAME)
INCLUDE=-I../include -I$(TOP)/../include/  $(BOOSTINCLUDE)

