#Major Makefile for file Library

# includefile contains Compiler definitions
TOP=../../..

export LIBNAME:=milog

include $(TOP)/conf/make.$(OSTYPE)

INCTO=$(TOP)/include/$(LIBNAME)
IIGNORE= -Iprivate -Ithread

include $(TOP)/conf/common.mk

#MILOGLN:=$(shell if [ ! -d milog ]; then ln -s include milog; fi)


LOCALIDIR:=$(LOCALDIR)/include/

INCLUDE=-I../include 
