version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: '1'
      KAFKA_CREATE_TOPICS: 'kvalobs.docker.raw:1:1,kvalobs.docker.checked:1:1,kvalobs.docker.decoded:1:1,kvalobs.docker.hint:1:1'
    volumes:
      - 'kvkafka:/kafka'

  postgres:
    image: kvpostgres:latest
    ports:
      - '5436:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - kvpostgres:/var/lib/postgresql/data


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

volumes:
  kvkafka:
  kvpostgres:
