Document: kvalobs
Title: Debian kvalobs Manual
Author: <insert document author here>
Abstract: This manual describes what kvalobs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kvalobs/kvalobs.sgml.gz

Format: postscript
Files: /usr/share/doc/kvalobs/kvalobs.ps.gz

Format: text
Files: /usr/share/doc/kvalobs/kvalobs.text.gz

Format: HTML
Index: /usr/share/doc/kvalobs/html/index.html
Files: /usr/share/doc/kvalobs/html/*.html

  
