#! /bin/sh

HTOP=`pwd`
KVDIR=$(cd ../../../..; pwd)

export KVDIR 


KVALOBSJAR=$KVDIR/src/service-libs/java/kvalobsclt.jar

export CLASSPATH=$KVALOBSJAR:$CLASSPATH
echo "CLASSPATH: $CLASSPATH"
echo "$@"

$KVDIR/share/kvalobs/java/bin/jaco "$@"
