usr/share/kvalobs/idl/*.idl

usr/include/kvalobs/kvsubscribe
usr/include/kvalobs/corbahelper
usr/include/kvalobs/decoder
usr/include/kvalobs/decodeutility
usr/include/kvalobs/dnmithread
usr/include/kvalobs/fileutil
usr/include/kvalobs/kvalobs
usr/include/kvalobs/kvdb
usr/include/kvalobs/kvskel
usr/include/kvalobs/miconfparser
usr/include/kvalobs/milog
usr/include/kvalobs/miutil

usr/lib/libkvalobs_kvsubscribe.a
usr/lib/libkvalobs_corbahelper.a
usr/lib/libkvalobs_decoderbase.a
usr/lib/libkvalobs_decodeutility.a
usr/lib/libkvalobs_dnmithread.a
usr/lib/libkvalobs_fileutil.a
usr/lib/libkvalobs_kvadmininterface.a
usr/lib/libkvalobs_kvalobs.a
usr/lib/libkvalobs_kvdb.a
usr/lib/libkvalobs_kvskel.a
usr/lib/libkvalobs_miconfparser.a
usr/lib/libkvalobs_milog.a
usr/lib/libkvalobs_miutil.a

usr/lib/libkvalobs_kvsubscribe.so
usr/lib/libkvalobs_corbahelper.so
usr/lib/libkvalobs_decoderbase.so
usr/lib/libkvalobs_decodeutility.so
usr/lib/libkvalobs_dnmithread.so
usr/lib/libkvalobs_fileutil.so
usr/lib/libkvalobs_kvadmininterface.so
usr/lib/libkvalobs_kvalobs.so

usr/lib/libkvalobs_kvdb.so
usr/lib/libkvalobs_kvskel.so
usr/lib/libkvalobs_miconfparser.so
usr/lib/libkvalobs_milog.so
usr/lib/libkvalobs_miutil.so

usr/lib/pkgconfig/libkvsubscribe.pc
usr/lib/pkgconfig/libkvalobs_corbahelper.pc
usr/lib/pkgconfig/libkvalobs_decoderbase.pc
usr/lib/pkgconfig/libkvalobs_decodeutility.pc
usr/lib/pkgconfig/libkvalobs_dnmithread.pc
usr/lib/pkgconfig/libkvalobs_fileutil.pc
usr/lib/pkgconfig/libkvalobs_kvadmininterface.pc
usr/lib/pkgconfig/libkvalobs_kvalobs.pc
usr/lib/pkgconfig/libkvalobs_kvdb.pc
usr/lib/pkgconfig/libkvalobs_kvskel.pc
usr/lib/pkgconfig/libkvalobs_miconfparser.pc
usr/lib/pkgconfig/libkvalobs_milog.pc
usr/lib/pkgconfig/libkvalobs_miutil.pc

