#Major Makefile for file Library

# includefile contains Compiler definitions
TOP=../../..
include $(TOP)/conf/make.$(OSTYPE)
include $(TOP)/conf/common.mk

export LIBNAME:=corbahelper


LOCALIDIR:=$(LOCALDIR)/include/$(LIBNAME)

INCLUDE=-I$(TOP)/../include  \
	    $(BOOSTINCLUDE) $(OMNIINCLUDE) 
