#!/bin/sh

DESTINATION=
DIRECTORIES="bin"
FILES=

THISTOP=`pwd`

if [ -f "kvpush" ]; then
    mkdir -p bin
    cp -fuv kvpush bin
else
    echo "BUILD FIRST: `pwd`"
    exit 0
fi

. $KVDIR/conf/INSTALL.conf

