/*
  Kvalobs - Free Quality Control Software for Meteorological Observations 

  Copyright (C) 2010 met.no

  Contact information:
  Norwegian Meteorological Institute
  Box 43 Blindern
  0313 OSLO
  NORWAY
  email: kvalobs-dev@met.no

  This file is part of KVALOBS

  KVALOBS is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License as 
  published by the Free Software Foundation; either version 2 
  of the License, or (at your option) any later version.
  
  KVALOBS is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.
  
  You should have received a copy of the GNU General Public License along 
  with KVALOBS; if not, write to the Free Software Foundation Inc., 
  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/


#ifndef EXCEPTION_H_
#define EXCEPTION_H_

#include <exception>
#include <string>

/**
 * Base class for exceptions used by qabase
 *
 * Subclasses may be generated by using the QABASE_EXCEPTION and
 * QABASE_DERIVED_EXCEPTION macros.
 *
 * \ingroup group_control
 */
class QabaseException : public std::exception
{
public:
	QabaseException(const std::string & what) : what_(what) {}
	virtual ~QabaseException() throw() {}

	const char * what() const throw()
	{
		return what_.c_str();
	}
private:
	std::string what_;
};


/**
 * Easy definition of QabaseException subclasses
 */
#define QABASE_EXCEPTION(name) \
class name : public QabaseException { \
public: \
	name(const std::string & msg) : QabaseException(msg) {} \
}

/**
 * Easy definition of exception subclasses derived from any class
 */
#define QABASE_DERIVED_EXCEPTION(name, derivedfrom) \
class name : public derivedfrom { \
public: \
	name(const std::string & msg) : derivedfrom(msg) {} \
}

#endif /* EXCEPTION_H_ */
