#Major Makefile for file Library

# includefile contains Compiler definitions
TOP=../../..
include $(TOP)/conf/make.$(OSTYPE)
include $(TOP)/conf/common.mk

export LIBNAME:=fileutil


LOCALIDIR:=$(LOCALDIR)/include/$(LIBNAME)

INCLUDE=
