#! /bin/sh

KVJAVA=$(cd ../..; pwd)
KVJAVA=$KVJAVA
export KVJAVA 



KVDIR=$KVJAVA

export KVDIR 

$KVDIR/share/kvalobs/java/bin/jaco -DKVALOBS=$KVDIR \
    -jar $KVDIR/share/kvalobs/java/lib/"$@"



