#! /bin/sh

TOP=$(cd ../..; pwd)
KVJAVA=$TOP/share/kvalobs/java
export KVJAVA 




KVDIR=$TOP

export KVDIR 

$KVDIR/share/kvalobs/java/bin/jaco -DKVALOBS=$KVDIR \
    -jar $KVDIR/share/kvalobs/java/lib/"$@"



