#! /bin/sh

KVDIR=$(cd ../..; pwd)

export KVDIR 


KVALOBSJAR=$KVDIR/share/kvalobs/java/lib/kvalobsclt.jar

export CLASSPATH=$KVALOBSJAR:$CLASSPATH
echo "CLASSPATH: $CLASSPATH"
echo "$@"

$KVDIR/share/kvalobs/java/bin/jaco "$@"
