#! /bin/sh

HERE=`pwd`
cd ../..;
TOP=`pwd`
cd $HERE;

pwd;
echo "Top: $TOP";

JLIB=$TOP/share/kvalobs/java/lib
BUILD=$HERE/build/metno/kvalobs
MYCLASSPATH=$JLIB/kvalobsclt.jar:$JLIB/postgresql-8.3-603.jdbc3.jar:$HERE/build:$BUILD/kl


echo "MYCLASSPATH: $MYCLASSPATH"

java -classpath $MYCLASSPATH metno.kvalobs.kl.dateregex "$@"
