/*
 Kvalobs - Free Quality Control Software for Meteorological Observations

 $Id: kvOperator.h,v 1.1.2.2 2007/09/27 09:02:30 paule Exp $

 Copyright (C) 2007 met.no

 Contact information:
 Norwegian Meteorological Institute
 Box 43 Blindern
 0313 OSLO
 NORWAY
 email: kvalobs-dev@met.no

 This file is part of KVALOBS

 KVALOBS is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 KVALOBS is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License along
 with KVALOBS; if not, write to the Free Software Foundation Inc.,
 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
#ifndef _kvOperator_h
#define _kvOperator_h

#include <kvalobs/kvDbBase.h>

/* autogenerated c++ header file from kv databasescript */

namespace kvalobs
{
/**
 * \addtogroup  dbinterface
 *
 * @{
 */

/**
 * \brief Interface to the table operator in the kvalobs database.
 *
 * This table is used for access control for the HQC application.
 */

class kvOperator: public kvDbBase
{
private:
	std::string username_;
	int userid_;

public:

	kvOperator()
	{
	}
	;
	kvOperator(const dnmi::db::DRow& r)
	{
		set(r);
	}
	kvOperator(const std::string& username, int userid)
	{
		set(username, userid);
	}

	bool set(const std::string& username, int userid);

	bool set(const dnmi::db::DRow&);
	const char* tableName() const
	{
		return "operator";
	}
	std::string toSend() const;
	std::string uniqueKey() const;

	/**
	 * \brief Name of a user that is permited to access HQC.
	 * \return A user name.
	 */
	const std::string & username() const
	{
		return username_;
	}

	/**
	 * \brief the userid for a that is permited to access HQC.
	 * \return The userid.
	 */
	int userID() const
	{
		return userid_;
	}

};
/** @} */
}
;

#endif

