# includefile contains Compiler definitions
TOP=../../..
include $(TOP)/conf/make.$(OSTYPE)
include $(TOP)/conf/common.mk

export LIBNAME:=dnmithread

LOCALIDIR:=$(LOCALDIR)/include/$(LIBNAME)
INCLUDE=$(BOOSTINCLUDE)


