#Major Makefile for file Library

# includefile contains Compiler definitions
TOP=../../..
include $(TOP)/conf/make.$(OSTYPE)
include $(TOP)/conf/common.mk

export LIBNAME:=miconfparser

#MICONFPARSERLN:=$(shell if [ ! -d miconfparser ]; \
#	                then ln -s include miconfparser; fi)

LOCALIDIR:=$(LOCALDIR)/include/$(LIBNAME)

INCLUDE=-I../include
