CREATE TABLE KV2KLIMA
(
  STNR         NUMERIC(12),
  DATO         TIMESTAMP,
  TYPEID       NUMERIC(4),
  PARAMID      NUMERIC(4),
  SENSOR       NUMERIC(1),
  XLEVEL       NUMERIC(2),
  ORIGINAL     NUMERIC(13,1),
  CORRECTED    NUMERIC(13,1),
  USEINFO      VARCHAR(16),
  PARA_NAME    VARCHAR(15),
  YEAR         NUMERIC(4),
  KVSTAMP      TIMESTAMP,
  KLSTAMP      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  OLD_NAME     VARCHAR(15),
  CONTROLINFO  VARCHAR(16),
  CFAILED      VARCHAR(200)
);

CREATE INDEX I_KV2KLIMA ON KV2KLIMA (STNR, DATO, TYPEID, PARAMID, SENSOR,
                                    XLEVEL, YEAR);


