CREATE TABLE T_TEXT_DATA
(
  STATIONID    INTEGER,
  OBSTIME      TIMESTAMP,
  ORIGINAL     VARCHAR(200),
  PARAMID      NUMERIC(15),
  TBTIME       TIMESTAMP,
  TYPEID       NUMERIC(5)
);

CREATE INDEX I_TEXT_DATA ON T_TEXT_DATA (STATIONID, OBSTIME, PARAMID, TYPEID);


