#!/bin/sh

DESTINATION=
DIRECTORIES="bin var/log var/kvsynop var/run share/kvsynop etc"
FILES=


THISTOP=`pwd`

if [ -f "kvsynopd" ]; then
    mkdir -p bin
    cp -fuv kvsynopclt bin
    cp -fuv kvsynopd bin
    cp -fuv kvsynopd_initdb bin
    cp -fuv kvsynopdparse bin
    cp -fuv kvsynopdbclt bin
    mkdir -p share/kvsynop
    cp -fuv createdb.sql share/kvsynop
else
    echo "BUILD FIRST: `pwd`"
    exit 0
fi

. $KVDIR/conf/INSTALL.conf

