#! /bin/sh

KVDIR=$KVALOBS/var/kvsynop/test/kvsynop
AODIR=$KVALOBS/var/kvsynop/test/aosynop
AOSYNOPDIR=synop
DIFDIR=$KVALOBS/var/kvsynop/test/aodif
KVSYNOP=$KVALOBS/bin/kvsynopdbclt
NAMEFILE=$KVALOBS/etc/name_vmono.txt

DATE=
TEST=
UNKNOWN=
NOCOPY=

while [ -n "$(echo \"$1\" | grep '-')" ]; do
    case $1 in
    -d ) DATE=$2
	shift;;
    -t ) TEST=TRUE;;
    -n ) NOCOPY=TRUE;;
    *  ) UNKNOWN=$1;;
    esac
    shift
done

echo "NOCOPY: $NOCOPY"

if [ "$DATE" ]; then
   FDATE=$(echo $DATE | sed -e 's/\([0-9]\+\)-\([0-9]\+\)-\([0-9]\+\) \+\([0-9]\+\)/\1\2\3/')
   FHOUR=$(echo $DATE | sed -e 's/\([0-9]\+\)-\([0-9]\+\)-\([0-9]\+\) \+\([0-9]\+\)/\4/')
else 
   DATE=$(date +'%F %H')
   FDATE=$(date +'%Y%m%d')
   FHOUR=$(date +'%H')
fi

echo "Date:  $DATE"
echo "FDate: $FDATE"
echo "FHour: $FHOUR"


NKVDIR=$KVDIR/$FDATE/$FHOUR
NAODIR=$AODIR/$FDATE/$FHOUR
NDIFDIR=$DIFDIR/$FDATE/$FHOUR

mkdir -p $NKVDIR
mkdir -p $NAODIR
mkdir -p $NDIFDIR

if [ -z "$NOCOPY" ]; then
   $KVSYNOP -f "${DATE}" -i $NAMEFILE -o $NKVDIR 
fi

NEWSYNOPS=$(ls -1 $NKVDIR)

if [ -z "$NOCOPY" ]; then
  for  FILE in $NEWSYNOPS ; do
     scp autoobs@autoobs:$AOSYNOPDIR/$FILE $NAODIR
#     cp -f $AOSYNOPDIR/$FILE $NAODIR
  done
fi

NDIF=0
NTOT=0

for  FILE in $NEWSYNOPS ; do
    diff -b -B -I 'S.NO..' $NKVDIR/$FILE $NAODIR/$FILE  > $NDIFDIR/$FILE 
    if [ $? -eq 0 ]; then
        echo "Exit: $?"
        rm -f $NDIFDIR/$FILE
	rm -f $NKVDIR/$FILE
	rm -f $NAODIR/$FILE
    else
	let NDIF=$NDIF+1
    fi
    let NTOT=$NTOT+1
done

echo "$NDIF files differ of $NTOT files!"

